# Generated by Django 5.0.1 on 2025-12-04 19:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_logo', models.TextField(blank=True, help_text='Imagen en base64 o ruta al archivo. Si está vacío, usa COMPANY_CONFIG["logo"] de settings.py', verbose_name='Logo de la Empresa')),
                ('company_name', models.CharField(blank=True, help_text='Si está vacío, usa COMPANY_CONFIG["name"] de settings.py', max_length=200, verbose_name='Nombre de la Empresa')),
                ('company_address', models.TextField(blank=True, help_text='Si está vacío, usa COMPANY_CONFIG["address"] de settings.py', verbose_name='Dirección')),
                ('company_phone', models.CharField(blank=True, help_text='Si está vacío, usa COMPANY_CONFIG["phone"] de settings.py', max_length=50, verbose_name='Teléfono')),
                ('company_email', models.EmailField(blank=True, help_text='Si está vacío, usa COMPANY_CONFIG["email"] de settings.py', max_length=254, verbose_name='Email')),
                ('company_website', models.URLField(blank=True, help_text='Si está vacío, usa COMPANY_CONFIG["website"] de settings.py', verbose_name='Sitio Web')),
                ('tax_id', models.CharField(blank=True, help_text='Si está vacío, usa COMPANY_CONFIG["tax_id"] de settings.py', max_length=50, verbose_name='RUC/NIT/RFC')),
                ('receipt_header', models.TextField(blank=True, help_text='Si está vacío, usa PRINTING_CONFIG["receipt_header"] de settings.py', verbose_name='Encabezado de Ticket')),
                ('receipt_footer', models.TextField(blank=True, help_text='Si está vacío, usa PRINTING_CONFIG["receipt_footer"] de settings.py', verbose_name='Pie de Ticket')),
                ('auto_print_receipt', models.BooleanField(default=True, help_text='Imprimir ticket al completar pago', verbose_name='Imprimir Ticket Automáticamente')),
                ('auto_print_kitchen', models.BooleanField(default=True, help_text='Imprimir orden de cocina al confirmar orden', verbose_name='Imprimir Orden de Cocina Automáticamente')),
                ('auto_open_drawer_on_payment', models.BooleanField(default=True, help_text='Abrir caja al imprimir ticket de venta', verbose_name='Abrir Caja Automáticamente al Pagar')),
                ('require_confirmation_to_open_drawer', models.BooleanField(default=False, help_text='Preguntar antes de abrir la caja', verbose_name='Requiere Confirmación para Abrir Caja')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Impresión',
                'verbose_name_plural': 'Configuraciones de Impresión',
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('printer_type', models.CharField(choices=[('thermal', 'Térmica (Tickets)'), ('laser', 'Láser (Facturas)'), ('matrix', 'Matriz de Puntos')], default='thermal', max_length=20, verbose_name='Tipo de Impresora')),
                ('connection_type', models.CharField(choices=[('usb', 'USB'), ('network', 'Red/IP'), ('bluetooth', 'Bluetooth'), ('serial', 'Serial/COM')], default='usb', max_length=20, verbose_name='Tipo de Conexión')),
                ('connection_string', models.CharField(help_text='USB: /dev/usb/lp0 | Red: 192.168.1.100 | COM: COM1', max_length=255, verbose_name='Cadena de Conexión')),
                ('port', models.IntegerField(blank=True, help_text='Puerto de red (ej: 9100 para impresoras ESC/POS)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='Puerto')),
                ('paper_width', models.IntegerField(default=80, help_text='58mm o 80mm típicamente', validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(210)], verbose_name='Ancho de Papel (mm)')),
                ('characters_per_line', models.IntegerField(default=42, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(80)], verbose_name='Caracteres por Línea')),
                ('has_cash_drawer', models.BooleanField(default=True, help_text='Si la impresora tiene caja de dinero conectada', verbose_name='Tiene Caja Registradora')),
                ('cash_drawer_pin', models.IntegerField(default=0, help_text='0 = Pin 2, 1 = Pin 5', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Pin de Caja')),
                ('cash_drawer_on_time', models.IntegerField(default=100, help_text='Tiempo que el pulso está activo', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Tiempo ON (ms)')),
                ('cash_drawer_off_time', models.IntegerField(default=100, help_text='Tiempo que el pulso está inactivo', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Tiempo OFF (ms)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_default', models.BooleanField(default=False, verbose_name='Impresora por Defecto')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configuración específica del driver', verbose_name='Configuración Adicional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impresora',
                'verbose_name_plural': 'Impresoras',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'is_default'], name='printer_pri_is_acti_de2fa0_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Número de Trabajo')),
                ('document_type', models.CharField(choices=[('receipt', 'Ticket'), ('invoice', 'Factura'), ('order', 'Orden'), ('report', 'Reporte'), ('other', 'Otro')], max_length=20, verbose_name='Tipo de Documento')),
                ('related_model', models.CharField(blank=True, help_text='Nombre del modelo relacionado (ej: Order, Payment)', max_length=50, verbose_name='Modelo Relacionado')),
                ('related_id', models.CharField(blank=True, help_text='ID del objeto relacionado', max_length=50, verbose_name='ID Relacionado')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('data', models.JSONField(default=dict, help_text='Datos usados para generar el contenido', verbose_name='Datos')),
                ('open_cash_drawer', models.BooleanField(default=False, help_text='Si se debe abrir la caja registradora al imprimir', verbose_name='Abrir Caja')),
                ('cash_drawer_opened', models.BooleanField(default=False, help_text='Si la caja fue abierta exitosamente', verbose_name='Caja Abierta')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('printing', 'Imprimiendo'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=20, verbose_name='Estado')),
                ('copies', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Copias')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='printer.printer', verbose_name='Impresora')),
            ],
            options={
                'verbose_name': 'Trabajo de Impresión',
                'verbose_name_plural': 'Trabajos de Impresión',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashDrawerEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('print', 'Apertura por Impresión'), ('manual', 'Apertura Manual'), ('register_open', 'Apertura de Turno'), ('register_close', 'Cierre de Turno'), ('test', 'Prueba')], default='print', max_length=20, verbose_name='Tipo de Evento')),
                ('success', models.BooleanField(default=True, verbose_name='Exitoso')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('triggered_by', models.CharField(blank=True, max_length=100, verbose_name='Activado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_drawer_events', to='printer.printer', verbose_name='Impresora')),
                ('print_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_drawer_events', to='printer.printjob', verbose_name='Trabajo de Impresión')),
            ],
            options={
                'verbose_name': 'Evento de Caja',
                'verbose_name_plural': 'Eventos de Caja',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('template_type', models.CharField(choices=[('receipt', 'Ticket de Venta'), ('invoice', 'Factura'), ('order_kitchen', 'Orden de Cocina'), ('order_bar', 'Orden de Bar'), ('daily_report', 'Reporte Diario'), ('cash_report', 'Reporte de Caja'), ('refund', 'Reembolso'), ('custom', 'Personalizado')], max_length=20, verbose_name='Tipo de Plantilla')),
                ('content', models.TextField(help_text='Plantilla con variables como {{order_number}}, {{total}}, etc.', verbose_name='Contenido de la Plantilla')),
                ('print_logo', models.BooleanField(default=True, verbose_name='Imprimir Logo')),
                ('print_qr', models.BooleanField(default=False, verbose_name='Imprimir QR')),
                ('auto_cut', models.BooleanField(default=True, help_text='Cortar papel automáticamente después de imprimir', verbose_name='Corte Automático')),
                ('copies', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Número de Copias')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_default', models.BooleanField(default=False, help_text='Plantilla por defecto para este tipo', verbose_name='Plantilla por Defecto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Impresión',
                'verbose_name_plural': 'Plantillas de Impresión',
                'ordering': ['template_type', 'name'],
                'indexes': [models.Index(fields=['template_type', 'is_active'], name='printer_pri_templat_d2f616_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='printtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('template_type',), name='unique_default_template_per_type'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='printer.printtemplate', verbose_name='Plantilla'),
        ),
        migrations.AddIndex(
            model_name='cashdrawerevent',
            index=models.Index(fields=['printer', 'created_at'], name='printer_cas_printer_2cae1c_idx'),
        ),
        migrations.AddIndex(
            model_name='cashdrawerevent',
            index=models.Index(fields=['event_type', 'created_at'], name='printer_cas_event_t_3b8ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='printjob',
            index=models.Index(fields=['printer', 'status'], name='printer_pri_printer_450ffb_idx'),
        ),
        migrations.AddIndex(
            model_name='printjob',
            index=models.Index(fields=['created_at', 'status'], name='printer_pri_created_bd032e_idx'),
        ),
        migrations.AddIndex(
            model_name='printjob',
            index=models.Index(fields=['document_type', 'created_at'], name='printer_pri_documen_29ed34_idx'),
        ),
    ]
