# Generated by Django 5.0.1 on 2026-06-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0002_alter_printjob_job_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='connection_type',
            field=models.CharField(choices=[('usb', 'USB'), ('network', 'Red/IP'), ('bluetooth', 'Bluetooth'), ('serial', 'Serial/COM'), ('rawbt', 'Inalámbrica (App RawBT)')], default='usb', max_length=20, verbose_name='Tipo de Conexión'),
        ),
    ]
