# Generated by Django 5.0.1 on 2025-12-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printjob',
            name='job_number',
            field=models.CharField(db_index=True, editable=False, max_length=35, unique=True, verbose_name='Número de Trabajo'),
        ),
    ]
