# Generated by Django 4.2.27 on 2026-01-27 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0006_pedido_fecha_confirmado_pedido_fecha_listo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Boda Familia Pérez', max_length=150)),
                ('fecha_evento', models.DateTimeField()),
                ('personas', models.IntegerField(default=10, verbose_name='Cantidad de Personas (Pax)')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador / Cotización'), ('confirmado', 'Confirmado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20)),
                ('presupuesto_por_persona', models.DecimalField(decimal_places=2, default=0, help_text='Precio de venta ofrecido por persona', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('costo_unitario_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='eventos.evento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='CostoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Ej: Meseros, Decoración, DJ', max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, help_text='Si lo cobras aparte (opcional)', max_digits=10)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_extra', to='eventos.evento')),
            ],
        ),
    ]
