# Generated by Django 4.2.28 on 2026-03-09 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMenaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CostoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Boda Familia Pérez', max_length=150)),
                ('fecha_evento', models.DateTimeField()),
                ('hora_evento', models.TimeField(blank=True, null=True)),
                ('personas', models.IntegerField(default=10, verbose_name='Cantidad de Personas (Pax)')),
                ('tipo_servicio', models.CharField(choices=[('buffet', 'Buffet'), ('plato_servido', 'Plato Servido'), ('cocktail', 'Cocktail'), ('otro', 'Otro')], default='plato_servido', max_length=50)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador / Cotización'), ('confirmado', 'Confirmado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20)),
                ('presupuesto_por_persona', models.DecimalField(decimal_places=2, default=0, help_text='Legacy: Precio venta por persona', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('costo_reposicion', models.DecimalField(decimal_places=2, help_text='Costo si se rompe/pierde', max_digits=10)),
                ('costo_alquiler', models.DecimalField(decimal_places=2, default=0, help_text='Costo de alquiler para el evento', max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='eventos.categoriamenaje')),
            ],
        ),
        migrations.CreateModel(
            name='ItemMenajeEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('costo_unitario_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_menaje', to='eventos.evento')),
                ('menaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.menaje')),
            ],
        ),
        migrations.CreateModel(
            name='IngresoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Menú Adulto Premium', max_length=150)),
                ('categoria', models.CharField(choices=[('menu_adulto', 'Menú Adultos'), ('menu_nino', 'Menú Niños'), ('bebidas', 'Bebidas/Licores'), ('servicios', 'Servicios Adicionales'), ('otros', 'Otros')], default='menu_adulto', max_length=50)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='GastoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('alquiler', 'Alquiler Equipos/Local'), ('ayb', 'Alimentos y Bebidas (Extra)'), ('decoracion', 'Decoración'), ('personal', 'Personal'), ('transporte', 'Transporte'), ('otros', 'Otros')], default='otros', max_length=50)),
                ('cantidad', models.IntegerField(default=1)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('costo_unitario_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='eventos.evento')),
            ],
        ),
    ]
