# Generated by Django 4.2.27 on 2026-01-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMenaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='hora_evento',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_servicio',
            field=models.CharField(choices=[('buffet', 'Buffet'), ('plato_servido', 'Plato Servido'), ('cocktail', 'Cocktail'), ('otro', 'Otro')], default='plato_servido', max_length=50),
        ),
        migrations.AlterField(
            model_name='costoadicional',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='costoadicional',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='evento',
            name='presupuesto_por_persona',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Legacy: Precio venta por persona', max_digits=10),
        ),
        migrations.CreateModel(
            name='Menaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('costo_reposicion', models.DecimalField(decimal_places=2, help_text='Costo si se rompe/pierde', max_digits=10)),
                ('costo_alquiler', models.DecimalField(decimal_places=2, default=0, help_text='Costo de alquiler para el evento', max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='eventos.categoriamenaje')),
            ],
        ),
        migrations.CreateModel(
            name='ItemMenajeEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('costo_unitario_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_menaje', to='eventos.evento')),
                ('menaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.menaje')),
            ],
        ),
        migrations.CreateModel(
            name='IngresoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Menú Adulto Premium', max_length=150)),
                ('categoria', models.CharField(choices=[('menu_adulto', 'Menú Adultos'), ('menu_nino', 'Menú Niños'), ('bebidas', 'Bebidas/Licores'), ('servicios', 'Servicios Adicionales'), ('otros', 'Otros')], default='menu_adulto', max_length=50)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='GastoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('alquiler', 'Alquiler Equipos/Local'), ('ayb', 'Alimentos y Bebidas (Extra)'), ('decoracion', 'Decoración'), ('personal', 'Personal'), ('transporte', 'Transporte'), ('otros', 'Otros')], default='otros', max_length=50)),
                ('cantidad', models.IntegerField(default=1)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='eventos.evento')),
            ],
        ),
    ]
