# Generated by Django 4.2.28 on 2026-03-09 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemenu',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.producto'),
        ),
        migrations.AddField(
            model_name='costoadicional',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_extra', to='eventos.evento'),
        ),
    ]
