# Generated by Django 4.2.29 on 2026-03-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_categoria_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='monto_recibido',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='vuelto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
