# Generated by Django 5.2.7 on 2026-01-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Notas para Cocina'),
        ),
    ]
