# Generated by Django 4.2.30 on 2026-05-05 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_fix_categoria_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Variante (ej: Mango)')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de esta Variante')),
                ('disponible', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='pedidos.producto')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Productos',
            },
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.varianteproducto', verbose_name='Variante/Sabor'),
        ),
    ]
