# Generated by Django 4.2.27 on 2026-01-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_confirmado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora enviado a Cocina'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_listo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora terminado en Cocina'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='notificacion_vista',
            field=models.BooleanField(default=False),
        ),
    ]
