# Generated by Django 4.2.30 on 2026-06-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_varianteproducto_detallepedido_variante'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='clave_acceso',
            field=models.CharField(blank=True, max_length=49, null=True, verbose_name='Clave de Acceso SRI'),
        ),
        migrations.AddField(
            model_name='factura',
            name='establecimiento',
            field=models.CharField(default='001', max_length=3, verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='factura',
            name='estado_sri',
            field=models.CharField(choices=[('borrador', 'Borrador (No enviada)'), ('pendiente', 'Pendiente de Autorización'), ('autorizado', 'Autorizado por el SRI'), ('rechazado', 'Rechazado'), ('devuelta', 'Devuelta')], default='borrador', max_length=20, verbose_name='Estado SRI'),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_autorizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Autorización SRI'),
        ),
        migrations.AddField(
            model_name='factura',
            name='metodo_pago_sri',
            field=models.CharField(choices=[('01', 'Sin utilización del sistema financiero (Efectivo)'), ('15', 'Compensación de deudas'), ('16', 'Tarjeta de débito'), ('19', 'Tarjeta de crédito'), ('20', 'Otros con utilización del sistema financiero'), ('21', 'Endoso de títulos')], default='01', max_length=2, verbose_name='Método de Pago SRI'),
        ),
        migrations.AddField(
            model_name='factura',
            name='punto_emision',
            field=models.CharField(default='001', max_length=3, verbose_name='Punto de Emisión'),
        ),
        migrations.AddField(
            model_name='factura',
            name='secuencial',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Secuencial SRI'),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_porcentaje_iva',
            field=models.CharField(choices=[('0', '0%'), ('2', '12%'), ('3', '14%'), ('4', '15%'), ('6', 'No Objeto'), ('7', 'Exento')], default='4', max_length=2, verbose_name='Código Porcentaje IVA SRI'),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_principal',
            field=models.CharField(blank=True, help_text='Ej: PL-001', max_length=50, null=True, verbose_name='Código Principal SRI'),
        ),
    ]
