# Generated by Django 4.2.27 on 2026-01-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_pedido_fecha_confirmado_pedido_fecha_listo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega/Reserva'),
        ),
    ]
