# Generated by Django 4.2.30 on 2026-06-01 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostal', '0005_reserva_usuario'),
        ('pedidos', '0007_factura_clave_acceso_factura_establecimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='origen',
            field=models.CharField(choices=[('cafeteria', 'Cafetería'), ('hostal', 'Hostal')], default='cafeteria', max_length=20, verbose_name='Módulo de Origen'),
        ),
        migrations.AddField(
            model_name='factura',
            name='reserva',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='hostal.reserva'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='pedido',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='pedidos.pedido'),
        ),
    ]
