# Generated by Django 4.2.30 on 2026-06-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_factura_origen_factura_reserva_alter_factura_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigo_porcentaje_iva',
        ),
        migrations.AddField(
            model_name='producto',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='Porcentaje IVA (%)'),
        ),
    ]
