# Generated by Django 5.0.1 on 2026-06-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_remove_producto_codigo_porcentaje_iva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='tipo_comprobante',
            field=models.CharField(choices=[('factura', 'Factura'), ('nota_entrega', 'Nota de Entrega')], default='factura', max_length=20),
        ),
    ]
