# Generated by Django 4.2.30 on 2026-06-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_identificacion',
            field=models.CharField(choices=[('04', 'RUC'), ('05', 'Cédula'), ('06', 'Pasaporte'), ('07', 'Consumidor Final'), ('08', 'Identificación del Exterior')], default='05', max_length=2, verbose_name='Tipo de Identificación SRI'),
        ),
    ]
