"""
Django settings for restaurante project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import pymysql
pymysql.install_as_MySQLdb()
import os
from dotenv import load_dotenv

load_dotenv()  # Load environment variables from .env file

import re
from django.core.exceptions import ValidationError

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
import sys
sys.path.append(os.path.join(BASE_DIR, 'app'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://0.0.0.0:8000',
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'axes',
    'core',
    'usuarios',
    'pedidos',
    'inventario',
    'clientes',
    'caja',
    'eventos.apps.EventosConfig',
    'hostal.apps.HostalConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # <--- Para servir archivos estáticos en producción
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'usuarios.middleware.UpdateLastActivityMiddleware', # Middleware propio
]

ROOT_URLCONF = 'restaurante.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'restaurante.wsgi.application'

# Axes para restrer y blockear el acceso
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    # El backend por defecto de Django
    'django.contrib.auth.backends.ModelBackend',
]

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'postorcafe_db'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD'),  
        'HOST': os.getenv('DB_HOST', 'db'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators


class SpecialCharacterValidator:
    def validate(self, password, user=None):
        if not re.search(r'[!@#$%^&*(),.?":{}|<>]', password):
            raise ValidationError(
                "La contraseña debe contener al menos un carácter especial.",
                code='password_no_special_char',
            )

    def get_help_text(self):
        return "Tu contraseña debe contener al menos un carácter especial."

AUTH_PASSWORD_VALIDATORS = [

  {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': {'min_length': 10}},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
    {'NAME': 'usuarios.validators.CustomPasswordValidator'},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True

# --- FORMATO REGIONAL (ESPAÑOL) ---
USE_L10N = True # Localización automática
USE_THOUSAND_SEPARATOR = True # Separador de miles (puntos)
DECIMAL_SEPARATOR = ',' # Separador decimal (coma)
THOUSAND_SEPARATOR = '.' # Separador miles (punto)


# --- CONFIGURACIÓN DE SEGURIDAD DE SESIONES ---
# Cierra la sesión al cerrar el navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# Tiempo de inactividad: 15 minutos (900 segundos)
SESSION_COOKIE_AGE = 900 
# Actualizar el tiempo de expiración en cada petición (para que sean 15 min de INACTIVIDAD, no absolutos)
SESSION_SAVE_EVERY_REQUEST = True
# Asegura que la cookie no se pueda acceder por JS
SESSION_COOKIE_HTTPONLY = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Compresión y caché para estáticos
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
WHITENOISE_MANIFEST_STRICT = False

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'usuarios.Usuario'
LOGIN_URL = '/usuarios/login/'
LOGOUT_REDIRECT_URL = '/usuarios/login/' # Con esto redirije a mi pagina de login 
LOGIN_REDIRECT_URL = '/'

# Configuracion de Jazzmin

JAZZMIN_SETTINGS = {
    # Títulos y Logos
    "site_title": "Postor Cafe San Pedro de Huaca",
    "site_header": "Postor Cafe San Pedro de Huaca",
    "site_brand": "Postor Cafe App",
    "welcome_sign": "Bienvenido al Panel de Control",
    "copyright": "Postor Cafe",
    
    # Menú lateral
    "search_model": ["usuarios.Usuario", "pedidos.Pedido"],

    # Iconos (Puedes añadir más aquí)
    "icons": {
        "auth": "fas fa-users-cog",
        "usuarios.Usuario": "fas fa-user",
        "usuarios.AuditLog": "fas fa-clipboard-list", # Icono de auditoría
        "pedidos.Mesa": "fas fa-chair",
        "pedidos.Producto": "fas fa-utensils",
        "pedidos.Pedido": "fas fa-receipt",
    },
    
    # Orden del menú lateral
    "order_with_respect_to": ["pedidos", "usuarios", "auth"],

    # Menú superior
    "topmenu_links": [
        {"name": "Ir al Sitio", "url": "/", "permissions": ["auth.view_user"]},
        {"name": "Cerrar Sesión", "url": "/admin/logout/", "new_window": False},
    ],

    # Opciones de interfaz
    "show_ui_builder": True,
    "show_sidebar_logout": True, # <-- Añadimos esto para que sea más visible
}
JAZZMIN_UI_TWEAKS = {
    "theme": "litera",
    "navbar": "navbar-white navbar-light",
    "sidebar": "sidebar-light-warning", 
    "accent": "accent-warning",
    "brand_colour": "navbar-warning",
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "button_classes": {
        "primary": "btn-warning",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# --- SECURITY HARDENING ---
# 1. Headers de Seguridad
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# 2. Configuración SSL/HTTPS (Basada en Variables de Entorno)
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True'
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False') == 'True'
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'False') == 'True'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# 3. HSTS (Strict Transport Security)
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Configuración de AXES
AXES_FAILURE_LIMIT = 5  # Bloqueo después de 5 intentos
AXES_COOLOFF_TIME = 0.25 # Bloqueo por 15 minutos (0.25 horas)
AXES_LOCKOUT_TEMPLATE = 'usuarios/lockout.html'
AXES_RESET_ON_SUCCESS = True
# Bloqueo por usuario E IP para mayor seguridad
AXES_LOCKOUT_PARAMETERS = ["username", "ip_address"]
# =============================
# Configuración de correo real (Gmail SMTP)
# =============================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Tu correo Gmail y contraseña de aplicación
# Tu correo Gmail y contraseña de aplicación
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# Dirección de envío por defecto
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Cierra la sesión si el navegador se cierra
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Sanitizar logs
SILENCED_SYSTEM_CHECKS = ["axes.W006"] if "ip_address" in AXES_LOCKOUT_PARAMETERS else []
