# Generated by Django 4.2.28 on 2026-03-09 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='pedidos.producto'),
        ),
        migrations.AddField(
            model_name='movimientokardex',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo'),
        ),
        migrations.AddField(
            model_name='movimientokardex',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor'),
        ),
        migrations.AddConstraint(
            model_name='receta',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('producto__isnull', False), ('insumo_principal__isnull', True)), models.Q(('producto__isnull', True), ('insumo_principal__isnull', False)), _connector='OR'), name='receta_solo_un_padre'),
        ),
    ]
