# Generated by Django 5.2.7 on 2026-01-21 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_receta_insumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='insumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo'),
        ),
    ]
