# Generated by Django 5.2.7 on 2026-01-21 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_receta_insumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='insumo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo'),
            preserve_default=False,
        ),
    ]
