# Generated by Django 5.2.7 on 2026-01-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_receta_insumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='cantidad_necesaria',
        ),
    ]
