# Generated by Django 5.2.7 on 2026-01-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_receta_cantidad_necesaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='cantidad_necesaria',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Cantidad para 1 plato', max_digits=10),
            preserve_default=False,
        ),
    ]
