# Generated by Django 4.2.27 on 2026-01-27 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_pedido_fecha_confirmado_pedido_fecha_listo_and_more'),
        ('inventario', '0006_receta_cantidad_necesaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='es_subreceta',
            field=models.BooleanField(default=False, help_text='Marcar si este insumo es una preparación (ej. Salsa de Tomate)'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='rendimiento_receta',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Cuánto rinde la receta de este insumo (en su unidad de medida)', max_digits=10),
        ),
        migrations.AddField(
            model_name='receta',
            name='insumo_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_de_receta', to='inventario.insumo'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='pedidos.producto'),
        ),
        migrations.AddConstraint(
            model_name='receta',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('producto__isnull', False), ('insumo_principal__isnull', True)), models.Q(('producto__isnull', True), ('insumo_principal__isnull', False)), _connector='OR'), name='receta_solo_un_padre'),
        ),
    ]
