# Generated by Django 4.2.29 on 2026-03-27 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caja', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción del Gasto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Gastado')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.CharField(choices=[('restaurante', 'Restaurante'), ('hostal', 'Hostal')], default='restaurante', max_length=20)),
                ('sesion_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='caja.sesioncaja')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
        ),
    ]
