# Generated by Django 4.2.29 on 2026-03-27 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostal', '0005_reserva_usuario'),
        ('caja', '0003_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='sesion_caja_hostal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos_hostal', to='hostal.sesioncajahostal'),
        ),
    ]
