# Generated by Django 4.2.29 on 2026-03-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostal', '0002_sesioncajahostal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipohabitacion',
            old_name='precio_noche',
            new_name='precio_persona',
        ),
    ]
