# Generated by Django 4.2.29 on 2026-03-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostal', '0003_remove_tipohabitacion_precio_noche_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipohabitacion',
            name='precio_persona',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
