# Generated by Django 4.2.30 on 2026-06-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostal', '0005_reserva_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='codigo_porcentaje_iva',
            field=models.CharField(choices=[('0', '0%'), ('2', '12%'), ('3', '14%'), ('4', '15%'), ('5', '5%'), ('6', 'No Objeto de Impuesto'), ('7', 'Exento de IVA')], default='4', max_length=2, verbose_name='Código Porcentaje IVA SRI'),
        ),
    ]
