# Generated by Django 4.2.30 on 2026-06-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(default='https://factuexpress.fronteratech.ec/api/sri/documents/create_and_process_invoice_complete/', help_text='URL completa del API de facturación', verbose_name='URL del Endpoint (Fronteratech)')),
                ('api_token', models.CharField(blank=True, help_text='Token de autenticación provisto por Fronteratech', max_length=255, null=True, verbose_name='Token VSR o Usuario')),
                ('ambiente', models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], default='1', max_length=1, verbose_name='Ambiente SRI')),
            ],
            options={
                'verbose_name': 'Configuración Facturación SRI',
                'verbose_name_plural': 'Configuración Facturación SRI',
            },
        ),
    ]
